language: node_js
node_js:
  - 12
addons:
  apt:
    packages:
      - libgconf-2-4
cache:
  npm: true
  directories:
    - ~/.cache
install:
  - yarn install
script:
  - yarn type-check
  - yarn test
  - yarn coverage
