# see https://github.com/cypress-io/circleci-orb
version: 2
jobs:
  build:
    docker:
      - image: cypress/base:10
        environment:
          TERM: xterm
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.cache  ## cache both yarn and Cypress!
      - run:
          name: Type Check
          command: yarn type-check
      - run:
          name: Tests
          command: yarn test
      - store_artifacts:
          path: /coverage
      - run:
          name: Coverage
          command: yarn report:coverage:text
      - run:
          name: Coverage
          command: yarn coverage
